/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACheckbox: typeof import('@arco-design/web-vue')['Checkbox']
    ACol: typeof import('@arco-design/web-vue')['Col']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AImage: typeof import('@arco-design/web-vue')['Image']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    ATree: typeof import('@arco-design/web-vue')['Tree']
    AttributeCard: typeof import('./src/components/AttributeCard.vue')['default']
    CardFooter: typeof import('./src/components/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/CardHeader.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
  }
}
